name: List Repositories
on:
  workflow_dispatch:

jobs:
  list_repositories:
    runs-on: ubuntu-latest

    steps:
      - name: List Repositories
        run: |
          gh auth login --with-token <<< "${{ secrets.GHUB_TOKEN }}"
          repos=$(gh repo list --json=name -q "org:<your_organization_name>" --limit 100 --jsonField=name)
          echo "$repos" | jq -r '.[].name'
